### ISSUE TITLE
Issues on Markbot

### ISSUE THREAD

**Issue by DDesousa0517** [DDesousa0517/horizontal-nav#1]
Having trouble understanding the issues indicated on Markbot...

<img width="912" alt="screen shot 2017-11-29 at 12 13 45 pm" src="https://user-images.githubusercontent.com/31852364/33388828-f98d698e-d4fe-11e7-9722-1eb6f451148d.png">

Issue one - I'm not sure where I am to put list-style-type?

Issue two - My hover is working perfectly when I use it in my browser so I don't understand why it is saying that it isn't working correctly?

Issue three - Again in the browser, it is showing the correct font so I don't understand why it is saying it is incorrect?

I have attached a copy of the Markbot screenshot... 

Thank you @thomasjbradley

Darcie

**Comment by DDesousa0517** [comment]
I have correct Issue 1... missed the "type" in my code.

**Comment by thomasjbradley** [comment]
*Re: hover—*

The `:hover` code needs to be applied to the `<a>` tag instead of the `<li>` tag:
https://github.com/DDesousa0517/horizontal-nav/blob/gh-pages/css/main.css#L52
This will also require moving the `padding` and a few other things off the `<li>` onto the `<a>` tags.

---

*Re: font—*

The problem with the font is not `Bevan`, but the backup font, `cursive`. You can't trust the code Google gives you because it's not always correct. In this case `Bevan` is a `serif` font not a cursive.

**Comment by DDesousa0517** [comment]
I really thought I was doing it right on the <li>, but I can see how it works better on the <a>. Whenever we bring fonts into our code off of Google... should we always delete the cursive and replace with either serif or sans-serif? 

Thank you for your help. Got one all by myself... my tutor will be proud lol
Darcie

**Comment by thomasjbradley** [comment]
Glad to hear you figured it out!

Yes, always replace `cursive`—unless you actually choose a cursive font in the Google Fonts interface.

**Comment by DDesousa0517** [comment]
Ok great - thanks again
